export enum MissionType {
  WIND_TURBINE_INSPECTION = 'WIND_TURBINE_INSPECTION',
  SOLAR_PANEL_SURVEY = 'SOLAR_PANEL_SURVEY',
  POWER_LINE_PATROL = 'POWER_LINE_PATROL',
}

export enum MissionStatus {
  PLANNED = 'PLANNED',
  PRE_FLIGHT_CHECK = 'PRE_FLIGHT_CHECK',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ABORTED = 'ABORTED',
}

export const NON_TERMINAL_MISSION_STATUSES = [
  MissionStatus.PLANNED,
  MissionStatus.PRE_FLIGHT_CHECK,
  MissionStatus.IN_PROGRESS,
];

export const TERMINAL_MISSION_STATUSES = [MissionStatus.COMPLETED, MissionStatus.ABORTED];
